name: Daily Security Scan

on:
  schedule:
    - cron: '0 5 * * *'  # Tous les jours à 5h UTC
  workflow_dispatch:     # Permet de déclencher manuellement

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nmap lynis xsltproc
        
    - name: Run Nmap scan
      run: |
        mkdir -p reports
        nmap -sV -T4 -O -F --script vuln -oN reports/nmap-report.txt 127.0.0.1
        xsltproc reports/nmap-report.txt -o reports/nmap-report.html
      
    - name: Run Lynis audit
      run: |
        mkdir -p reports
        sudo lynis audit system --quick --no-colors --logfile reports/lynis-report.log
        grep -E 'warning|suggestion' reports/lynis-report.log > reports/lynis-critical.txt
        
    - uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: reports/
